const mongoose=require('mongoose')
const movieSchema= new mongoose.Schema({
    movieName:{
        type:String,
        required:true
    },
    releaseDate:{
        type:String,
        required:true
    },
    movieLength:{
        type:String,
        required:true
    },
    movieLanguage:{
        type:String,
        required:true
    },
    rottenRating:{
        type:String,
        required:true
    },
    imdbRating:{
        type:String,
        required:true
    },
    movieGenre:{
        type:String,
        required:true
    },
    movieThumbnail:{
        type:String,
        required:true
    },
    moviePoster:{
        type:String,
        required:true
    },
    movieTrailer:{
        type:String,
        required:true
    },
    movieFrom:{
        type:String,
        required:true
    },
    movieTo:{
        type:String,
        required:true
    },
    screensShowing:{
        type:String,
        required:true
    },
    movieAbout:{
        type:String,
        required:true
    },
    userId:{
        type:String,
        required:true
    }
})
const movie=mongoose.model('movie',movieSchema)
module.exports=movie